"""remove image

Revision ID: 4a36bf9f803d
Revises: a0c405e09ed3
Create Date: 2023-09-23 09:08:12.212676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a36bf9f803d'
down_revision = 'a0c405e09ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.drop_column('image_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_content', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
